version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar

  sonarqube:
    image: sonarqube
    ports:
      - '9000:9000'
      - '9092:9092'
    volumes:
      - $PWD/data/sonar:/opt/sonarqube/data
    depends_on:
       - db
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar